CREATE TABLE dbo.Marca(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nome VARCHAR(250) NOT NULL,
);

GO
	
CREATE TABLE dbo.Modelo(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nome VARCHAR(250) NOT NULL,
	MarcaID INT FOREIGN KEY REFERENCES dbo.Marca(ID) NOT NULL
);

GO


CREATE TABLE dbo.Versao(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nome VARCHAR(250) NOT NULL,
	ModeloID INT FOREIGN KEY REFERENCES dbo.Modelo(ID) NOT NULL
);

GO


CREATE TABLE dbo.Veiculo(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Imagem VARCHAR(500) NULL,
	Quilometragem INT NULL,
	Preco DECIMAL NULL, 
	AnoModelo INT NOT NULL, 
	AnoFabricao INT NOT NULL, 
	Cor VARCHAR(250),
	MarcaID INT FOREIGN KEY REFERENCES dbo.Marca(ID) NOT NULL,
	ModeloID INT FOREIGN KEY REFERENCES dbo.Modelo(ID) NOT NULL,
	VersaoID INT FOREIGN KEY REFERENCES dbo.Versao(ID) NOT NULL,
);

GO


CREATE TABLE dbo.Carro(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Ano INT NOT NULL,
	Quilometragem INT NULL,
	Observacao VARCHAR(500) NULL,
	MarcaID INT FOREIGN KEY REFERENCES dbo.Marca(ID) NOT NULL,
	ModeloID INT FOREIGN KEY REFERENCES dbo.Modelo(ID) NOT NULL,
	VersaoID INT FOREIGN KEY REFERENCES dbo.Versao(ID) NOT NULL
);